set(_CATKIN_CURRENT_PACKAGE "active_vision_msgs")
set(active_vision_msgs_VERSION "0.0.0")
set(active_vision_msgs_MAINTAINER "onr <onr@todo.todo>")
set(active_vision_msgs_PACKAGE_FORMAT "2")
set(active_vision_msgs_BUILD_DEPENDS "cv_bridge" "roscpp" "image_transport" "std_msgs" "sensor_msgs" "message_generation")
set(active_vision_msgs_BUILD_EXPORT_DEPENDS "cv_bridge" "roscpp" "image_transport" "std_msgs" "sensor_msgs" "message_generation")
set(active_vision_msgs_BUILDTOOL_DEPENDS "catkin")
set(active_vision_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(active_vision_msgs_EXEC_DEPENDS "cv_bridge" "roscpp" "image_transport" "std_msgs" "sensor_msgs" "message_runtime")
set(active_vision_msgs_RUN_DEPENDS "cv_bridge" "roscpp" "image_transport" "std_msgs" "sensor_msgs" "message_runtime" "message_generation")
set(active_vision_msgs_TEST_DEPENDS )
set(active_vision_msgs_DOC_DEPENDS )
set(active_vision_msgs_URL_WEBSITE "")
set(active_vision_msgs_URL_BUGTRACKER "")
set(active_vision_msgs_URL_REPOSITORY "")
set(active_vision_msgs_DEPRECATED "")