# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from active_vision_msgs/Vision_Message.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Vision_Message(genpy.Message):
  _md5sum = "9e12f5951169920222965062c93aead0"
  _type = "active_vision_msgs/Vision_Message"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string Frameid
geometry_msgs/Point32 Pos
bool Found

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['Frameid','Pos','Found']
  _slot_types = ['string','geometry_msgs/Point32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Frameid,Pos,Found

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Vision_Message, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Frameid is None:
        self.Frameid = ''
      if self.Pos is None:
        self.Pos = geometry_msgs.msg.Point32()
      if self.Found is None:
        self.Found = False
    else:
      self.Frameid = ''
      self.Pos = geometry_msgs.msg.Point32()
      self.Found = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.Frameid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3fB().pack(_x.Pos.x, _x.Pos.y, _x.Pos.z, _x.Found))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.Pos is None:
        self.Pos = geometry_msgs.msg.Point32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Frameid = str[start:end].decode('utf-8')
      else:
        self.Frameid = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.Pos.x, _x.Pos.y, _x.Pos.z, _x.Found,) = _get_struct_3fB().unpack(str[start:end])
      self.Found = bool(self.Found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.Frameid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3fB().pack(_x.Pos.x, _x.Pos.y, _x.Pos.z, _x.Found))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.Pos is None:
        self.Pos = geometry_msgs.msg.Point32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Frameid = str[start:end].decode('utf-8')
      else:
        self.Frameid = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.Pos.x, _x.Pos.y, _x.Pos.z, _x.Found,) = _get_struct_3fB().unpack(str[start:end])
      self.Found = bool(self.Found)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fB = None
def _get_struct_3fB():
    global _struct_3fB
    if _struct_3fB is None:
        _struct_3fB = struct.Struct("<3fB")
    return _struct_3fB
